### ISSUE TITLE
Define the mapping between the benchflow-configuration file and the Faban configuration

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/drivers-maker#8]
We always need to keep the mappings between our configuration file and the faban configuration files.

We agreed that we are going to map the configuration by first generating a run.yml corresponding to the run.xml command, so that then the /convert method will simply convert the run.yml to run.xml

**Comment by VincenzoFerme** [comment]
@simonedavico we need to start with this, now that we are starting to change it.

**Comment by VincenzoFerme** [comment]
In the `run.xml` file we also need the list of collectors to be contacted by the driver at `start` and `stop` time (see https://github.com/benchflow/collectors/issues/38#issuecomment-184417147). The port of the collector is determined at runtime, so we need to resolve it through [benchflow/compose](). For doing that we need the list of the services name as they are defined in the `docker-compose.yml` file generated for the deployment. Since we also need to know the endpoint of these services to be called at `start` and `stop` time, a possible structure of this information in yml (then directly translated to xml) could be:

```yml
benchflow-services-configuration:
	collectors:
	   enabled: [stats,mysqldump]
	   endpoints:
	      stats_start: /start
	      stats_stop: /stop
	      mysqldump_stop: /data
```

**Comment by simonedavico** [comment]
We decided to modify the structure of the list of collectors specified under `benchflow-services-configuration` like follows:

```yaml
collectors:
    stats:
         start: /start
         stop: /stop
    mysqldump:
         stop: /data
```
